### PR TITLE
code clean for kind version.

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

flake update for test code.

### CODE REVIEW

**Comment by pydctw** [comment]
Many thanks @yanggangtony for the contribution!

I see you already signed the contributor license agreement. Once the check is done, I will merge the PR.

**Comment by yanggangtony** [comment]
> Many thanks @yanggangtony for the contribution!
> 
> I see you already signed the contributor license agreement. Once the check is done, I will merge the PR.

Thanks for review..
Got it.

**Comment by yanggangtony** [comment]
Hey, is there any one provide a demo for the 'signed contributor license agreement.'?
I tried 2 times, but still failed..
Maybe too difficult for me to sign it ..:flushed::flushed:

**Comment by pydctw** [comment]
> Hey, is there any one provide a demo for the 'signed contributor license agreement.'? I tried 2 times, but still failed.. Maybe too difficult for me to sign it ..😳😳

I haven't seen the CLA as an employee. Did you provide the name of org and full street address on CLA? 
> Please provide the name of the organization you are affiliated with or indicate none; Please provide full street address.

If you did, I will try to contact the open source team to figure out.

**Comment by yanggangtony** [comment]
image

上海道客网络科技有限公司 , 
上海市杨浦区江湾城路99号尚浦中心6号楼7楼

**Comment by pydctw** [comment]
@yanggangtony, I am working with our open source office to figure out and will let you know the findings. Thanks for your patience.

**Comment by yanggangtony** [comment]
@pydctw 
thanks for follow these case.:yum::yum:

**Comment by yanggangtony** [comment]
Hi , community.
Is there a sign method for chinese name and Chinese character?
Or just sign in english?

**Pull request closed without merging**
